#!/usr/bin/env node
// Generated by create-project-calavera for the HTML Validate integration.
//
// Runs `html-validate` with the given files or patterns, and exits 0 without
// running it when no file matches. `html-validate` exits 1 when no file
// matches and has no option to allow empty input, so a project without static
// HTML files would fail `lint:html`. HTML Validate's own file expansion decides
// what matches, so `.htmlvalidateignore` applies here as it does in the CLI.
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

import { CLI } from "html-validate";

const patterns = process.argv.slice(2);

if (patterns.length === 0) {
  process.stderr.write('Pass the HTML files or patterns to validate, for example "**/*.html".\n');
  process.exit(2);
}

const files = await new CLI().expandFiles(patterns);

if (files.length === 0) {
  process.stdout.write(
    `No files match ${patterns.join(" ")}, so HTML Validate has nothing to check.\n`,
  );
} else {
  const require = createRequire(import.meta.url);
  const manifestPath = require.resolve("html-validate/package.json");
  const { bin } = require(manifestPath);
  const result = spawnSync(
    process.execPath,
    [join(dirname(manifestPath), bin["html-validate"]), ...patterns],
    { stdio: "inherit" },
  );

  if (result.error) {
    throw new Error(`Could not run html-validate: ${result.error.message}`, {
      cause: result.error,
    });
  }

  process.exitCode = result.status ?? 1;
}
