export const integrationCatalog = [
  {
    id: "editorconfig",
    label: "EditorConfig",
    group: "Project consistency",
    platform: "generic",
    status: "recommended",
    dependencies: [],
  },
  {
    id: "knip",
    label: "Knip",
    group: "Unused code",
    platform: "knip",
    status: "optional",
    minimumCliVersion: "2.3.0",
    dependencies: ["knip"],
  },
  {
    id: "html-validate",
    label: "HTML Validate",
    group: "HTML",
    platform: "html-validate",
    status: "optional",
    minimumCliVersion: "2.3.0",
    dependencies: ["html-validate"],
    htmlValidate: {
      extends: ["html-validate:recommended", "html-validate:document"],
      rules: {},
    },
  },
  {
    id: "varlock",
    label: "Varlock",
    group: "Environment variables",
    platform: "varlock",
    status: "optional",
    minimumCliVersion: "2.3.0",
    dependencies: ["varlock"],
  },
  {
    id: "github-repository-controls",
    label: "GitHub repository controls",
    group: "Repository governance",
    platform: "github",
    status: "optional",
    minimumCliVersion: "2.5.0",
    dependencies: [],
  },
  {
    id: "react-doctor",
    label: "React Doctor",
    group: "React best practices",
    platform: "react-doctor",
    status: "framework-specific",
    dependencies: ["react-doctor"],
  },
  {
    id: "stylelint",
    label: "Stylelint",
    group: "CSS linting",
    platform: "stylelint",
    status: "recommended",
    dependencies: ["stylelint"],
  },
  {
    id: "stylelint-standard",
    label: "Stylelint standard config",
    group: "CSS linting",
    platform: "stylelint-config",
    status: "recommended",
    dependencies: ["stylelint-config-standard"],
    includes: ["stylelint"],
    stylelint: {
      extends: ["stylelint-config-standard"],
    },
  },
  {
    id: "stylelint-order",
    label: "CSS property ordering",
    group: "CSS property ordering",
    platform: "stylelint-plugin",
    status: "optional",
    dependencies: ["stylelint-order"],
    includes: ["stylelint"],
    stylelint: {
      plugins: ["stylelint-order"],
      rules: {
        "order/properties-alphabetical-order": true,
      },
    },
  },
  {
    id: "stylelint-baseline",
    label: "CSS Baseline",
    group: "CSS Baseline",
    platform: "stylelint-plugin",
    status: "recommended",
    dependencies: ["stylelint-plugin-use-baseline"],
    includes: ["stylelint"],
    stylelint: {
      plugins: ["stylelint-plugin-use-baseline"],
      rules: {
        "plugin/use-baseline": true,
      },
    },
  },
  {
    id: "stylelint-scss",
    label: "SCSS support",
    group: "CSS linting",
    platform: "stylelint-plugin",
    status: "framework-specific",
    dependencies: ["stylelint-scss", "stylelint-config-standard-scss"],
    includes: ["stylelint"],
    stylelint: {
      extends: ["stylelint-config-standard-scss"],
      plugins: ["stylelint-scss"],
    },
  },
  {
    id: "stylelint-stylistic",
    label: "Stylelint stylistic rules",
    group: "CSS linting",
    platform: "stylelint-config",
    status: "optional",
    dependencies: ["@stylistic/stylelint-config"],
    includes: ["stylelint"],
    stylelint: {
      extends: ["@stylistic/stylelint-config"],
    },
  },
  {
    id: "stylelint-logical-css",
    label: "Logical CSS",
    group: "CSS logical properties",
    platform: "stylelint-plugin",
    status: "optional",
    minimumCliVersion: "2.3.0",
    dependencies: ["stylelint-plugin-logical-css"],
    includes: ["stylelint"],
    stylelint: {
      extends: ["stylelint-plugin-logical-css/configs/recommended"],
      plugins: ["stylelint-plugin-logical-css"],
    },
  },
  {
    id: "css-property-type-validator",
    label: "CSS property type validation",
    group: "CSS property type validation",
    platform: "stylelint-plugin",
    status: "experimental",
    dependencies: ["@schalkneethling/stylelint-plugin-css-property-type-validator"],
    includes: ["stylelint"],
    stylelint: {
      plugins: ["@schalkneethling/stylelint-plugin-css-property-type-validator"],
      rules: {
        "css-property-type-validator/valid-property-types": true,
      },
    },
  },
  {
    id: "prettier",
    label: "Prettier",
    group: "Formatting",
    platform: "prettier",
    status: "recommended",
    dependencies: ["prettier"],
  },
  {
    id: "prettier-tailwind",
    label: "Tailwind class sorting",
    group: "Formatting",
    platform: "prettier-plugin",
    status: "optional",
    dependencies: ["prettier-plugin-tailwindcss"],
    includes: ["prettier"],
    prettier: { plugins: ["prettier-plugin-tailwindcss"] },
  },
  {
    id: "prettier-svelte",
    label: "Svelte formatting",
    group: "Formatting",
    platform: "prettier-plugin",
    status: "framework-specific",
    dependencies: ["prettier-plugin-svelte"],
    includes: ["prettier"],
    prettier: { plugins: ["prettier-plugin-svelte"] },
  },
  {
    id: "prettier-astro",
    label: "Astro formatting",
    group: "Formatting",
    platform: "prettier-plugin",
    status: "framework-specific",
    dependencies: ["prettier-plugin-astro"],
    includes: ["prettier"],
    prettier: { plugins: ["prettier-plugin-astro"] },
  },
];
