export const integrationCatalog = [
  {
    id: "editorconfig",
    label: "EditorConfig",
    group: "Project consistency",
    platform: "generic",
    status: "recommended",
    dependencies: [],
  },
  {
    id: "typescript",
    label: "TypeScript type checking",
    group: "Type checking",
    platform: "typescript",
    status: "recommended",
    dependencies: ["typescript", "@types/node"],
  },
  {
    id: "oxlint",
    label: "Oxlint",
    group: "Modern JS/TS linting",
    platform: "oxlint",
    status: "recommended",
    dependencies: ["oxlint"],
  },
  {
    id: "oxlint-eslint",
    label: "Oxc ESLint compatibility rules",
    group: "Modern JS/TS linting",
    platform: "oxlint-plugin",
    plugin: "eslint",
    status: "recommended",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-typescript",
    label: "Oxc TypeScript rules",
    group: "Modern JS/TS linting",
    platform: "oxlint-plugin",
    plugin: "typescript",
    status: "recommended",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-unicorn",
    label: "Oxc Unicorn rules",
    group: "Modern JS/TS linting",
    platform: "oxlint-plugin",
    plugin: "unicorn",
    status: "recommended",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-oxc",
    label: "Oxc native rules",
    group: "Modern JS/TS linting",
    platform: "oxlint-plugin",
    plugin: "oxc",
    status: "recommended",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-import",
    label: "Imports and modules",
    group: "Imports and modules",
    platform: "oxlint-plugin",
    plugin: "import",
    status: "optional",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-react",
    label: "Oxc React best practices",
    group: "React best practices",
    platform: "oxlint-plugin",
    plugin: "react",
    status: "framework-specific",
    includes: ["oxlint"],
  },
  {
    id: "react-doctor",
    label: "React Doctor",
    group: "React best practices",
    platform: "react-doctor",
    status: "framework-specific",
    dependencies: ["react-doctor"],
  },
  {
    id: "oxlint-jsx-a11y",
    label: "Accessibility",
    group: "Accessibility",
    platform: "oxlint-plugin",
    plugin: "jsx-a11y",
    status: "optional",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-node",
    label: "Node package rules",
    group: "Node package rules",
    platform: "oxlint-plugin",
    plugin: "node",
    status: "optional",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-promise",
    label: "Promise safety",
    group: "Promise safety",
    platform: "oxlint-plugin",
    plugin: "promise",
    status: "optional",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-vitest",
    label: "Vitest rules",
    group: "Test rules",
    platform: "oxlint-plugin",
    plugin: "vitest",
    status: "optional",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-jest",
    label: "Jest rules",
    group: "Test rules",
    platform: "oxlint-plugin",
    plugin: "jest",
    status: "optional",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-nextjs",
    label: "Next.js rules",
    group: "Framework rules",
    platform: "oxlint-plugin",
    plugin: "nextjs",
    status: "framework-specific",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-vue",
    label: "Vue rules",
    group: "Framework rules",
    platform: "oxlint-plugin",
    plugin: "vue",
    status: "framework-specific",
    includes: ["oxlint"],
  },
  {
    id: "oxlint-jsdoc",
    label: "JSDoc rules",
    group: "Documentation rules",
    platform: "oxlint-plugin",
    plugin: "jsdoc",
    status: "optional",
    includes: ["oxlint"],
  },
  {
    id: "oxfmt",
    label: "Oxfmt",
    group: "Formatting",
    platform: "oxfmt",
    status: "experimental",
    dependencies: ["oxfmt"],
  },
  {
    id: "eslint",
    label: "ESLint flat config",
    group: "Classic JS/TS linting",
    platform: "eslint",
    status: "recommended",
    dependencies: ["eslint", "@eslint/js", "globals"],
  },
  {
    id: "typescript-eslint",
    label: "TypeScript ESLint",
    group: "Classic JS/TS linting",
    platform: "eslint-plugin",
    status: "recommended",
    dependencies: ["typescript-eslint"],
    includes: ["eslint", "typescript"],
  },
  {
    id: "eslint-config-prettier",
    label: "Prettier compatibility",
    group: "Formatting",
    platform: "eslint-plugin",
    status: "recommended",
    dependencies: ["eslint-config-prettier"],
    includes: ["eslint"],
  },
  {
    id: "eslint-react",
    label: "ESLint React best practices",
    group: "React best practices",
    platform: "eslint-plugin",
    status: "framework-specific",
    dependencies: ["eslint-plugin-react", "eslint-plugin-react-hooks"],
    includes: ["eslint"],
  },
  {
    id: "eslint-jsx-a11y",
    label: "Accessibility",
    group: "Accessibility",
    platform: "eslint-plugin",
    status: "optional",
    dependencies: ["eslint-plugin-jsx-a11y"],
    includes: ["eslint"],
  },
  {
    id: "eslint-import",
    label: "Imports and modules",
    group: "Imports and modules",
    platform: "eslint-plugin",
    status: "optional",
    dependencies: ["eslint-plugin-import-x"],
    includes: ["eslint"],
  },
  {
    id: "eslint-n",
    label: "Node package rules",
    group: "Node package rules",
    platform: "eslint-plugin",
    status: "optional",
    dependencies: ["eslint-plugin-n"],
    includes: ["eslint"],
  },
  {
    id: "eslint-promise",
    label: "Promise safety",
    group: "Promise safety",
    platform: "eslint-plugin",
    status: "optional",
    dependencies: ["eslint-plugin-promise"],
    includes: ["eslint"],
  },
  {
    id: "eslint-unicorn",
    label: "Unicorn rules",
    group: "Classic JS/TS linting",
    platform: "eslint-plugin",
    status: "optional",
    dependencies: ["eslint-plugin-unicorn"],
    includes: ["eslint"],
  },
  {
    id: "eslint-sonarjs",
    label: "SonarJS rules",
    group: "Classic JS/TS linting",
    platform: "eslint-plugin",
    status: "optional",
    dependencies: ["eslint-plugin-sonarjs"],
    includes: ["eslint"],
  },
  {
    id: "eslint-vitest",
    label: "Vitest rules",
    group: "Test rules",
    platform: "eslint-plugin",
    status: "optional",
    dependencies: ["@vitest/eslint-plugin"],
    includes: ["eslint"],
  },
  {
    id: "eslint-jest",
    label: "Jest rules",
    group: "Test rules",
    platform: "eslint-plugin",
    status: "optional",
    dependencies: ["eslint-plugin-jest"],
    includes: ["eslint"],
  },
  {
    id: "stylelint",
    label: "Stylelint",
    group: "CSS linting",
    platform: "stylelint",
    status: "recommended",
    dependencies: ["stylelint"],
  },
  {
    id: "stylelint-standard",
    label: "Stylelint standard config",
    group: "CSS linting",
    platform: "stylelint-config",
    status: "recommended",
    dependencies: ["stylelint-config-standard"],
    includes: ["stylelint"],
    stylelint: {
      extends: ["stylelint-config-standard"],
    },
  },
  {
    id: "stylelint-order",
    label: "CSS property ordering",
    group: "CSS property ordering",
    platform: "stylelint-plugin",
    status: "optional",
    dependencies: ["stylelint-order"],
    includes: ["stylelint"],
    stylelint: {
      plugins: ["stylelint-order"],
      rules: {
        "order/properties-alphabetical-order": true,
      },
    },
  },
  {
    id: "stylelint-baseline",
    label: "CSS Baseline",
    group: "CSS Baseline",
    platform: "stylelint-plugin",
    status: "recommended",
    dependencies: ["stylelint-plugin-use-baseline"],
    includes: ["stylelint"],
    stylelint: {
      plugins: ["stylelint-plugin-use-baseline"],
      rules: {
        "plugin/use-baseline": true,
      },
    },
  },
  {
    id: "stylelint-scss",
    label: "SCSS support",
    group: "CSS linting",
    platform: "stylelint-plugin",
    status: "framework-specific",
    dependencies: ["stylelint-scss", "stylelint-config-standard-scss"],
    includes: ["stylelint"],
    stylelint: {
      extends: ["stylelint-config-standard-scss"],
      plugins: ["stylelint-scss"],
    },
  },
  {
    id: "stylelint-stylistic",
    label: "Stylelint stylistic rules",
    group: "CSS linting",
    platform: "stylelint-config",
    status: "optional",
    dependencies: ["@stylistic/stylelint-config"],
    includes: ["stylelint"],
    stylelint: {
      extends: ["@stylistic/stylelint-config"],
    },
  },
  {
    id: "css-property-type-validator",
    label: "CSS property type validation",
    group: "CSS property type validation",
    platform: "stylelint-plugin",
    status: "experimental",
    dependencies: ["@schalkneethling/stylelint-plugin-css-property-type-validator"],
    includes: ["stylelint"],
    stylelint: {
      plugins: ["@schalkneethling/stylelint-plugin-css-property-type-validator"],
      rules: {
        "css-property-type-validator/valid-property-types": true,
      },
    },
  },
  {
    id: "prettier",
    label: "Prettier",
    group: "Formatting",
    platform: "prettier",
    status: "recommended",
    dependencies: ["prettier"],
  },
  {
    id: "prettier-tailwind",
    label: "Tailwind class sorting",
    group: "Formatting",
    platform: "prettier-plugin",
    status: "optional",
    dependencies: ["prettier-plugin-tailwindcss"],
    includes: ["prettier"],
  },
  {
    id: "prettier-svelte",
    label: "Svelte formatting",
    group: "Formatting",
    platform: "prettier-plugin",
    status: "framework-specific",
    dependencies: ["prettier-plugin-svelte"],
    includes: ["prettier"],
  },
  {
    id: "prettier-astro",
    label: "Astro formatting",
    group: "Formatting",
    platform: "prettier-plugin",
    status: "framework-specific",
    dependencies: ["prettier-plugin-astro"],
    includes: ["prettier"],
  },
];
