// @ts-check
import { cp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";

import { artifactPayloadPath } from "@schalkneethling/calavera-artifact-core/node";

import { fileExists } from "../utils/fs.js";
import { isNotEmptyString, isPlainObject } from "../utils/guards.js";
import { hashDirectory, hashFile, textHash } from "../utils/hash.js";
import { aiArtifactCatalog, DEFAULT_AI_TARGET } from "./catalog.js";

/**
 * @typedef {import("../state.js").CalaveraState} CalaveraState
 *
 * @typedef {"skill" | "hook" | "agent"} AiArtifactType
 *
 * @typedef {object} AiItemConfig
 * @property {string} [id]
 * @property {string} [type]
 * @property {string} [src]
 * @property {string} [target]
 *
 * @typedef {object} NormalizedAiItem
 * @property {string} [id]
 * @property {string} type
 * @property {string} src
 * @property {string} [target]
 *
 * @typedef {object} ResolvedAiArtifact
 * @property {number} index
 * @property {string} sourcePath
 * @property {string} source
 * @property {string} name
 * @property {AiArtifactType} type
 * @property {string} path
 * @property {string} [target]
 *
 * @typedef {object} AiArtifactState
 * @property {AiArtifactType} type
 * @property {string} name
 * @property {string} source
 * @property {string} path
 * @property {string} hash
 * @property {string} [target]
 *
 * @typedef {{ type: string, path: string, category?: "ai", aiType?: AiArtifactType, name?: string, reason?: string }} AiChange
 */

const AI_SOURCE_DIRECTORIES = Object.freeze({
  skill: "skills",
  hook: "hooks",
  agent: "agents",
});

const AI_HOOK_FILES = Object.freeze(["hook.mjs", "settings-fragment.json"]);
const CODEX_AGENT_TARGET = "codex";

/**
 * @param {ResolvedAiArtifact} artifact
 * @returns {boolean}
 */
function isCodexAgentArtifact(artifact) {
  return artifact.type === "agent" && artifact.target === CODEX_AGENT_TARGET;
}

/**
 * @param {string} value
 * @returns {string}
 */
function tomlString(value) {
  return JSON.stringify(value);
}

/**
 * @param {string} frontmatter
 * @returns {Record<string, string>}
 */
function parseSimpleFrontmatter(frontmatter) {
  /** @type {Record<string, string>} */
  const fields = {};

  for (const line of frontmatter.split("\n")) {
    const separatorIndex = line.indexOf(":");

    if (separatorIndex <= 0) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();

    if (key) {
      fields[key] = value;
    }
  }

  return fields;
}

/**
 * @param {string} markdown
 * @returns {{ frontmatter: Record<string, string>, body: string }}
 */
function parseAgentMarkdown(markdown) {
  const normalized = markdown.replaceAll("\r\n", "\n");

  if (!normalized.startsWith("---\n")) {
    throw new Error("Agent Markdown must start with YAML frontmatter.");
  }

  const closingMarker = normalized.indexOf("\n---\n", 4);

  if (closingMarker === -1) {
    throw new Error("Agent Markdown must include closing YAML frontmatter.");
  }

  return {
    frontmatter: parseSimpleFrontmatter(normalized.slice(4, closingMarker)),
    body: normalized.slice(closingMarker + "\n---\n".length).trim(),
  };
}

/**
 * @param {string} markdown
 * @returns {string}
 */
export function createCodexAgentToml(markdown) {
  const { frontmatter, body } = parseAgentMarkdown(markdown);
  const name = frontmatter.name;
  const description = frontmatter.description;

  if (!isNotEmptyString(name) || !isNotEmptyString(description) || !isNotEmptyString(body)) {
    throw new Error(
      "Codex agent adapter requires source Markdown with name, description, and body instructions.",
    );
  }

  const lines = [
    "# Generated by create-project-calavera from a bundled Markdown agent.",
    "# Source model metadata is omitted because Codex custom agents use Codex model IDs.",
    `name = ${tomlString(name)}`,
    `description = ${tomlString(description)}`,
    `developer_instructions = ${tomlString(body)}`,
  ];

  return `${lines.join("\n")}\n`;
}

/**
 * @param {string} type
 * @param {number} index
 * @returns {AiArtifactType}
 */
function normalizeAiItemType(type, index) {
  if (Object.hasOwn(AI_SOURCE_DIRECTORIES, type)) {
    return /** @type {AiArtifactType} */ (type);
  }

  throw new Error(
    `AI item at index ${index} has unsupported type "${type}". Supported types: skill, hook, agent.`,
  );
}

/**
 * @param {unknown} value
 * @returns {value is AiItemConfig}
 */
function isAiItemConfig(value) {
  return (
    isPlainObject(value) &&
    ((isNotEmptyString(value.id) && value.type === undefined && value.src === undefined) ||
      (isNotEmptyString(value.type) && isNotEmptyString(value.src) && value.id === undefined)) &&
    (value.target === undefined || isNotEmptyString(value.target))
  );
}

/**
 * @param {AiArtifactType} type
 * @param {AiItemConfig} item
 * @param {number} index
 * @returns {string | undefined}
 */
function normalizeAiTarget(type, item, index) {
  if (type === "skill") {
    if (item.target !== undefined) {
      throw new Error(`AI item at index ${index} target only applies to hook and agent items.`);
    }

    return undefined;
  }

  const target = item.target?.trim() || DEFAULT_AI_TARGET;

  if (target.includes("/") || target.includes("\\") || target === "." || target === "..") {
    throw new Error(
      `AI item at index ${index} target must be a single directory name without path separators or traversal.`,
    );
  }

  return target;
}

/**
 * @param {unknown} aiConfig
 * @returns {NormalizedAiItem[]}
 */
function normalizeAiItems(aiConfig) {
  if (aiConfig === undefined) {
    return [];
  }

  if (!Array.isArray(aiConfig)) {
    throw new Error("The optional ai config key must be an array.");
  }

  return aiConfig.map((entry, index) => {
    if (!isAiItemConfig(entry)) {
      throw new Error(`AI item at index ${index} must contain id, or legacy type and src fields.`);
    }

    if (entry.id) {
      const artifact = aiArtifactCatalog.find(({ id }) => id === entry.id);
      if (!artifact) throw new Error(`AI item at index ${index} has unknown id "${entry.id}".`);
      const target = entry.target?.trim();
      if (target && artifact.targets && !artifact.targets.includes(target)) {
        throw new Error(`AI item at index ${index} target is not supported by ${entry.id}.`);
      }
      return {
        id: artifact.id,
        type: artifact.type,
        src: artifact.src,
        target,
      };
    }

    return {
      type: /** @type {string} */ (entry.type).trim(),
      src: /** @type {string} */ (entry.src).trim(),
      target: entry.target?.trim(),
    };
  });
}

/**
 * @param {string} src
 * @param {number} index
 * @param {AiArtifactType} type
 * @returns {string}
 */
function resolveAiSourcePath(src, index, type) {
  const artifact = aiArtifactCatalog.find((candidate) => candidate.src === src);

  if (!artifact) {
    throw new Error(`AI item at index ${index} source must stay within src/ai/: ${src}.`);
  }

  if (artifact.type !== type) {
    throw new Error(
      `AI item at index ${index} ${type} source must be under ${AI_SOURCE_DIRECTORIES[type]}/: ${src}.`,
    );
  }

  return artifactPayloadPath(src);
}

/**
 * @param {AiArtifactType} type
 * @param {string} sourcePath
 * @param {number} index
 * @returns {string}
 */
function inferAiSourceName(type, sourcePath, index) {
  if (type === "agent") {
    if (!sourcePath.endsWith(".md")) {
      throw new Error(
        `AI item at index ${index} agent source must point to a Markdown file: ${sourcePath}.`,
      );
    }

    return basename(sourcePath, ".md");
  }

  return basename(sourcePath);
}

/**
 * @param {AiArtifactType} type
 * @param {string} name
 * @param {string | undefined} target
 * @returns {string}
 */
function aiInstallPath(type, name, target) {
  if (type === "skill") {
    return join(".agents", "skills", name);
  }

  if (!target) {
    throw new Error(`AI ${type} items require an output target.`);
  }

  if (type === "hook") {
    return join(".agents", "hooks", target, `${name}.mjs`);
  }

  if (target === CODEX_AGENT_TARGET) {
    return join(".codex", "agents", `${name}.toml`);
  }

  return join(".agents", "agents", target, `${name}.md`);
}

/**
 * @param {string} hookPath
 * @returns {string}
 */
function hookSettingsInstallPath(hookPath) {
  return join(dirname(hookPath), `${basename(hookPath, ".mjs")}.settings-fragment.json`);
}

/**
 * @param {{ type: AiArtifactType, path: string }} artifact
 * @returns {string[]}
 */
export function aiArtifactOutputPaths(artifact) {
  return artifact.type === "hook"
    ? [artifact.path, hookSettingsInstallPath(artifact.path)]
    : [artifact.path];
}

/**
 * @param {string} directory
 * @returns {Promise<string>}
 */
async function hashHookDirectory(directory) {
  const hashes = await Promise.all(
    AI_HOOK_FILES.map((fileName) => hashFile(join(directory, fileName))),
  );
  return hashes.join(".");
}

/**
 * @param {string} hookPath
 * @returns {Promise<string>}
 */
async function hashHookInstall(hookPath) {
  const settingsPath = hookSettingsInstallPath(hookPath);
  const hashes = [await hashFile(hookPath)];

  if (await fileExists(settingsPath)) {
    hashes.push(await hashFile(settingsPath));
  }

  return hashes.join(".");
}

/**
 * @param {AiArtifactType} type
 * @param {string} sourcePath
 * @param {number} index
 */
export async function assertAiSourceExists(type, sourcePath, index) {
  let sourceStats;

  try {
    sourceStats = await stat(sourcePath);
  } catch {
    throw new Error(`AI item at index ${index} references missing ${type} source: ${sourcePath}.`);
  }

  const isExpectedKind = type === "agent" ? sourceStats.isFile() : sourceStats.isDirectory();

  if (!isExpectedKind) {
    throw new Error(
      `AI item at index ${index} expected ${type} source "${sourcePath}" to be a ${type === "agent" ? "file" : "directory"}.`,
    );
  }
}

/**
 * @param {AiArtifactType} type
 * @param {string} sourcePath
 * @param {string | undefined} target
 * @returns {Promise<string>}
 */
async function hashAiSource(type, sourcePath, target) {
  if (type === "skill") {
    return hashDirectory(sourcePath);
  }

  if (type === "hook") {
    return hashHookDirectory(sourcePath);
  }

  if (target === CODEX_AGENT_TARGET) {
    return textHash(createCodexAgentToml(await readFile(sourcePath, "utf8")));
  }

  return hashFile(sourcePath);
}

/**
 * @param {AiArtifactType} type
 * @param {string} installPath
 * @param {string} [target]
 * @returns {Promise<string>}
 */
export async function hashAiInstall(type, installPath, target) {
  if (type === "skill") {
    return hashDirectory(installPath);
  }

  if (type === "hook") {
    return hashFile(installPath);
  }

  if (target === CODEX_AGENT_TARGET) {
    return textHash(await readFile(installPath, "utf8"));
  }

  return hashFile(installPath);
}

/**
 * @param {{ ai?: unknown }} recipe
 * @returns {ResolvedAiArtifact[]}
 */
export function resolveAiArtifacts(recipe, sourcePaths = new Map()) {
  /** @type {Map<string, ResolvedAiArtifact>} */
  const deduped = new Map();

  for (const [index, item] of normalizeAiItems(recipe.ai).entries()) {
    const type = normalizeAiItemType(item.type, index);
    const target = normalizeAiTarget(type, item, index);
    const sourcePath =
      sourcePaths.get(item.id ?? item.src) ?? resolveAiSourcePath(item.src, index, type);
    const name = inferAiSourceName(type, item.src, index);
    const key = [type, target, name].filter(Boolean).join(":");

    if (!deduped.has(key)) {
      deduped.set(key, {
        index,
        sourcePath,
        source: item.id ?? item.src,
        name,
        target,
        type,
        path: aiInstallPath(type, name, target),
      });
    }
  }

  return [...deduped.values()];
}

/**
 * @param {CalaveraState} state
 * @param {string} path
 * @returns {AiArtifactState | undefined}
 */
function stateAiArtifactForPath(state, path) {
  return state.aiArtifacts.find((artifact) => artifact.path === path);
}

/**
 * @param {ResolvedAiArtifact} artifact
 * @param {string} [outputRoot]
 */
async function copyAiArtifact(artifact, outputRoot) {
  const installPath = outputRoot ? resolve(outputRoot, artifact.path) : resolve(artifact.path);

  if (artifact.type === "skill") {
    await mkdir(dirname(installPath), { recursive: true });
    await rm(installPath, { force: true, recursive: true });
    await cp(artifact.sourcePath, installPath, { recursive: true });
    return;
  }

  await mkdir(dirname(installPath), { recursive: true });

  if (artifact.type === "hook") {
    await writeFile(installPath, await readFile(join(artifact.sourcePath, "hook.mjs")));
    await writeFile(
      hookSettingsInstallPath(installPath),
      await readFile(join(artifact.sourcePath, "settings-fragment.json")),
    );

    return;
  }

  if (isCodexAgentArtifact(artifact)) {
    await writeFile(installPath, createCodexAgentToml(await readFile(artifact.sourcePath, "utf8")));
    return;
  }

  await writeFile(installPath, await readFile(artifact.sourcePath));
}

/**
 * @param {ResolvedAiArtifact} artifact
 * @param {string} path
 * @param {string} sourceHash
 * @param {CalaveraState} previousState
 */
async function assertSafeAiWrite(artifact, path, sourceHash, previousState) {
  if (!(await fileExists(path))) {
    return;
  }

  const installedHash = await hashAiInstall(artifact.type, path, artifact.target);

  if (installedHash === sourceHash) {
    return;
  }

  const stateArtifact = stateAiArtifactForPath(previousState, path);

  if (stateArtifact?.hash === installedHash) {
    return;
  }

  if (
    artifact.type === "hook" &&
    path === artifact.path &&
    stateArtifact?.hash === (await hashHookInstall(artifact.path))
  ) {
    return;
  }

  const reason = stateArtifact
    ? `It appears to have local edits (installed=${installedHash}, state=${stateArtifact.hash}).`
    : "It is not recorded as Calavera-managed.";

  throw new Error(`Refusing to overwrite existing AI artifact: ${path}. ${reason}`);
}

/**
 * @param {{ ai?: unknown }} recipe
 * @param {{ dryRun: boolean, outputRoot?: string }} options
 * @param {CalaveraState} previousState
 * @returns {Promise<{ artifacts: AiArtifactState[], changes: AiChange[], pointers: string[] }>}
 */
export async function buildAiApplyResult(recipe, options, previousState, sourcePaths = new Map()) {
  const artifacts = resolveAiArtifacts(recipe, sourcePaths);
  /** @type {AiChange[]} */
  const changes = [];
  /** @type {AiArtifactState[]} */
  const stateArtifacts = [];
  /** @type {Set<string>} */
  const pointerSet = new Set();

  for (const artifact of artifacts) {
    await assertAiSourceExists(artifact.type, artifact.sourcePath, artifact.index);
    const outputPaths = aiArtifactOutputPaths(artifact);
    const sourceHashes =
      artifact.type === "hook"
        ? await Promise.all([
            hashFile(join(artifact.sourcePath, "hook.mjs")),
            hashFile(join(artifact.sourcePath, "settings-fragment.json")),
          ])
        : [await hashAiSource(artifact.type, artifact.sourcePath, artifact.target)];
    let needsWrite = false;

    for (const [outputIndex, path] of outputPaths.entries()) {
      const sourceHash = sourceHashes[outputIndex];
      if (!sourceHash) {
        throw new Error(`Missing source hash for AI artifact output: ${path}.`);
      }
      stateArtifacts.push({
        type: artifact.type,
        name: artifact.name,
        source: artifact.source,
        target: artifact.target,
        path,
        hash: sourceHash,
      });
      const upToDate =
        (await fileExists(path)) &&
        (await hashAiInstall(artifact.type, path, artifact.target)) === sourceHash;
      if (upToDate) continue;

      await assertSafeAiWrite(artifact, path, sourceHash, previousState);
      needsWrite = true;
      changes.push({
        type: "write",
        path,
        category: "ai",
        aiType: artifact.type,
        name: artifact.name,
      });
    }

    if (needsWrite && !options.dryRun) {
      await copyAiArtifact(artifact, options.outputRoot);
    }

    if (artifact.type === "skill") {
      pointerSet.add("Installed skills are available under .agents/skills/.");
    }

    if (artifact.type === "hook") {
      pointerSet.add(
        `Hook scripts for ${artifact.target} are installed under .agents/hooks/${artifact.target}/. Review bundled settings-fragment.json files before wiring them into agent settings.`,
      );
    }

    if (artifact.type === "agent") {
      pointerSet.add(
        isCodexAgentArtifact(artifact)
          ? "Codex custom agent files are installed under .codex/agents/."
          : `Agent files for ${artifact.target} are installed under .agents/agents/${artifact.target}/ in their original Markdown/frontmatter format.`,
      );
    }
  }

  return {
    artifacts: stateArtifacts,
    changes,
    pointers: [...pointerSet],
  };
}
